version: "3.8"

services:

  app:
    build:
      args:
        user: ${SYSTEM_USER_ID}
        uid: ${SYSTEM_USERNAME}
      context: .
      dockerfile: docker/php/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}/php
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/report.sql.gz:/seed/report.sql.gz
    networks:
      - app-network

  nginx:
    image: nginx:1.18
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local